# -*- coding: utf-8 -*-
"""yield-curve-monitor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPnCDIgoBaQnE8Y6vCPvaHdrBN7Z4VVT
"""

import numpy as np
import pandas as np
import yfinance as yf
import matplotlib.pyplot as plt

# Parameters
start_date = '2015-01-01'
end_date = None

tickers = {
    "5Y":"^FVX",
    "10Y":"^TNX",
    "30Y":"^TYX"
}

# Data downloading
data = yf.download(
    list(tickers.values()),
    start=start_date,
    end=end_date,
    auto_adjust=True,
    progress=False
)["Close"]

data.columns = tickers.keys()

yields=data.dropna().copy()

print(yields.tail())

# Spreads construction in basis points
curve = yields.copy()
curve["10s5s_bps"] = (curve["10Y"] - curve["5Y"])*100
curve["30s10s_bps"] = (curve["30Y"] - curve["10Y"])*100

for col in ["5Y","10Y","30Y"]:
  curve[f"{col}_chg_bps"] = curve[col].diff()*100

curve["level_chg_bps"] = curve["10Y"].diff() * 100 # Benchmark
curve["slope_chg_bps"] = curve["10s5s_bps"].diff()
curve = curve.dropna()

# Regime classification

def classify_regime(level_chg, slope_chg):
    if level_chg < 0 and slope_chg > 0:
        return "Bull Steepening"
    if level_chg < 0 and slope_chg < 0:
        return "Bull Flattening"
    if level_chg > 0 and slope_chg > 0:
        return "Bear Steepening"
    if level_chg > 0 and slope_chg < 0:
        return "Bear Flattening"
    return "Neutral"

curve["regime"] = [
    classify_regime(lv, sl)
    for lv, sl in zip(curve["level_chg_bps"], curve["slope_chg_bps"])
]

print(curve[["level_chg_bps", "slope_chg_bps", "regime"]].tail(10))

yields.plot()
plt.title("US Yield Curve Proxies — Levels (%)")
plt.xlabel("Date")
plt.ylabel("Yield (%)")
plt.grid(True)
plt.tight_layout()
plt.show()

curve[["10s5s_bps", "30s10s_bps"]].plot()
plt.title("Yield Curve Slopes (basis points)")
plt.xlabel("Date")
plt.ylabel("bps")
plt.grid(True)
plt.tight_layout()
plt.show()

regime_counts = curve["regime"].value_counts()

regime_counts.plot(kind="bar")
plt.title("Yield Curve Regimes — Frequency")
plt.xlabel("Regime")
plt.ylabel("Number of days")
plt.grid(True)
plt.tight_layout()
plt.show()

print(regime_counts)